language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email: "ftoueix@nexfol.com"

matrix:
  fast_finish: true
